build:
  image: node:6
  commands:
    - "npm install"
    - "npm install buildgoggles@0.2.0-3"
    - "./node_modules/buildgoggles/bin/buildgoggles --releaseOwner=jgreat --releaseBranch=master"

cache:
  mount:
    - node_modules
    - .git

publish:
  # Publish to DockerHub
  docker:
    image: leankit/drone-docker
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: jgreat/vote-demo-worker
    storage_driver: overlay
  # Publish a Rancher Catalog
  rancher-catalog:
    image: jgreat/drone-rancher-catalog
    docker_username: $$DOCKER_USER
    docker_password: $$DOCKER_PASS
    docker_repo: jgreat/vote-demo-worker
    catalog_repo: jgreat/rancher-vote-demo-worker
    github_token: $$GITHUB_TOKEN
    github_user: jgreat
    github_email: jgreat@jgreat.me

deploy:
  # Deploy to Rancher Enviornment via Cowpoke Service
  cowpoke:
    image: leankit/drone-cowpoke:catalog-upgrade
    cowpoke_url: https://cowpoke.leankitdev.com
    cowpoke_port: 8000
    cowpoke_api_key: $$COWPOKE_API_KEY
    cowpoke_catalog: rancher-vote-demo-worker
    cowpoke_catalog_upgrade: 'true'
    docker_owner: jgreat
